Updates README.md to use correct name for package/container type
actions/delete-package-versions pull request #166
Opened 2024-03-12 14:56 UTC by nweiler

Updated to use correct name for package/container type.

2024-03-12 15:34 UTC, cwille97 commented
@nweiler Thank you for your contribution. This tool does support [containers](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) so the README is correct.

2024-03-12 16:04 UTC, nweiler commented
Ok. My usage suggests that the tool does in fact support containers but that the tag 'containers' does not work and 'docker' does.

2024-03-12 19:05 UTC, nweiler commented
@cwille97 For example, here is the output from two separate GitHub actions runs. I have redacted some sensitive info. AFAIK the only difference between the two runs is the name change:

## SUCCESS
```
Run actions/delete-package-versions@v4
  with:
    owner: XXXXXXXX
    package-name: XXXXXXXX
    package-type: docker
    num-old-versions-to-delete: 10
    delete-only-pre-release-versions: false
    delete-only-untagged-versions: false
    token: ***
    min-versions-to-keep: -1
    ignore-versions: ^$
Total versions deleted till now: 10
```

## FAIL
```
Run actions/delete-package-versions@v4
  with:
    owner: XXXXXXXX
    package-name: XXXXXXXX
    package-type: container
    num-old-versions-to-delete: 10
    delete-only-pre-release-versions: false
    delete-only-untagged-versions: false
    token: ***
    min-versions-to-keep: -1
    ignore-versions: ^$
Error: get versions API failed. Package not found.
```

2024-03-13 16:57 UTC, kalinon commented
`package-type: container` works for me in v5. Try the new version.

2024-03-14 12:58 UTC, cwille97 requested changes

2024-03-14 12:58 UTC, cwille97 commented on README.md
> +  # Type of the package. Can be one of docker, maven, npm, nuget, or rubygems.
```suggestion
  # Type of the package. Can be one of docker (v4 or older), container (v5 or newer), maven, npm, nuget, or rubygems.
```

2024-03-14 13:21 UTC, nweiler commented on README.md
> +  # Type of the package. Can be one of docker, maven, npm, nuget, or rubygems.
Beautiful! Thank you for your input.

2024-03-14 13:49 UTC, cwille97 approved these changes
LGTM, thanks for the docs update!

2024-03-14 13:50 UTC, merged